---
# Preety Print the  

resources:
  pipelines:
  - pipeline: securitylib # Name of the pipeline resource.
    source: TestCallPipeline # The name of the pipeline referenced by this pipeline resource.
    trigger: true # Run app-ci pipeline when any run of security-lib-ci completes

trigger:
  branches:
    include:
      - main

  tags:
    include:
      - '*'

parameters:
- name: trigger_type
  displayName: Select trigger type
  type: string
  default: CI
  values:
  - CI
  - Release
  - EOS
- name: sprint_number
  displayName: Sprint Number
  type: string
  default: " "

variables:
- name: buildTimeStamp # will be set by script
- name: buildNum

stages:

- stage: Initialize
  pool: 
   name: Azure-GitHub
   demands:
    - agent.name -equals AZ-GH
  jobs:
  - job: Checkout
    timeoutInMinutes: 0
    displayName: 'Checkout'
    steps:
    - checkout: self 
      clean: true
