---
# Preety Print the  
trigger:
  branches:
    include:
      - main

  tags:
    include:
      - '*'

variables:
- name: buildTimeStamp # will be set by script
- name: buildNum

stages:

- stage: Initialize
  pool: 
   name: Azure-GitHub
   demands:
    - agent.name -equals AZ-GH
  jobs:
  - job: Checkout
    timeoutInMinutes: 0
    displayName: 'Checkout'
    steps:
    - checkout: none 
      clean: true

    - task: PowerShell@2
      inputs:
       targetType: 'inline'
       script: |
        $pat = [Convert]::ToBase64String([Text.Encoding]::ASCII.GetBytes(":iyj3a262zaa33swytf55j3hwczjwyf2tytnsqvizt3mlaktnfpma"))
        
        write-host "Auth print"

          $body =@{
          definition = @{
          id = 68        
          }
          templateParameters = @{
          sprint_number= 66
          }
          }| ConvertTo-Json
                  
          write-host $body

          try {

          $params = @{'Uri' = ('https://hlsi01-poc.visualstudio.com/USHC_AMER_US_ADU_HSP_Ua3/_apis/build/builds?api-version=6.1-preview.6')
          'Headers'= @{'Authorization' = 'Basic ' + $pat}
          'Method'= 'Post'
          'ContentType' = 'application/json'
          'Body'= ($body)}
          $result = Invoke-RestMethod @params
          write-host $result
          }
          catch {
          Write-Host "An error occurred:"
          Write-Host $_.ScriptStackTrace
          }



