---
# Preety Print the  
trigger:
  branches:
    include:
      - main

  tags:
    include:
      - '*'

parameters:
- name: trigger_type
  displayName: Select trigger type
  type: string
  default: CI
  values:
  - CI
  - Release
  - EOS
- name: sprint_number
  displayName: Sprint Number
  type: string
  default: " "

variables:
- name: buildTimeStamp # will be set by script
- name: buildNum

stages:

- stage: Initialize
  pool: 
   name: Azure-GitHub
   demands:
    - agent.name -equals AZ-GH
  jobs:
  - job: Checkout
    timeoutInMinutes: 0
    displayName: 'Checkout'
    steps:
    - checkout: none 
      clean: true

    - task: PowerShell@2
      inputs:
       targetType: 'inline'
       script: |
        $AzureDevOpsAuthenicationHeader = @{Authorization = 'Basic ' + [Convert]::ToBase64String([Text.Encoding]::ASCII.GetBytes("$(AdoUserid):$(AdoPassword)")) }
        write-host $AzureDevOpsAuthenicationHeader
        $body =@{
          definition = @{
            id = 68        
           }
          templateParameters = @{ sprint_number= "test123" }
        }| ConvertTo-Json
        write-host $body
        $response = Invoke-RestMethod -Uri "https://hlsi01-poc.visualstudio.com/USHC_AMER_US_ADU_HSP_Ua3/_apis/build/builds?api-version=6.1-preview.6" -Method 'POST'-ContentType "application/json" -Body $body -Headers $AzureDevOpsAuthenicationHeader 
        write-host "The Job id is: $($response.job)"
      
