---
# Preety Print the  
trigger:
  branches:
    include:
      - main

  tags:
    include:
      - '*'

variables:
- name: buildTimeStamp # will be set by script
- name: buildNum

stages:

- stage: Initialize
  pool: 
   name: Azure-GitHub
   demands:
    - agent.name -equals AZ-GH
  jobs:
  - job: Checkout
    timeoutInMinutes: 0
    displayName: 'Checkout'
    steps:
    - checkout: none 
      clean: true

    - task: PowerShell@2
      inputs:
       targetType: 'inline'
       script: |
        $pat = [Convert]::ToBase64String([Text.Encoding]::ASCII.GetBytes("iyj3a262zaa33swytf55j3hwczjwyf2tytnsqvizt3mlaktnfpma"))
        $AzureDevOpsAuthenicationHeader = @{Authorization = 'Basic ' + [Convert]::ToBase64String([Text.Encoding]::ASCII.GetBytes("$(AdoUserid):$(AdoPassword)")) }
        write-host "Auth print"
        write-host $AzureDevOpsAuthenicationHeader

        $bodytest =@{
         extra_vars = @{
          artif_base_url ='https://gwproductengineering.jfrog.io/artifactory/mms-cms-cef-generic-dev'
          hpaPackageName="test"
          message_store_database_server ='hpasdevsql001.dev.mapshc.com,8443'
          message_store_database_server_hipaa ='hpasdevsql001.dev.mapshc.com,8443'
          plan_event_database_server='hpasdevsql001.dev.mapshc.com,8443'
          security_database_server='hpasdevsql001.dev.mapshc.com,8443'
          connect_biz_talk_server= 'hpasdevweb01.dev.mapshc.com'
          manager_fqdn= "hpasdevbas02.dev.mapshc.com"
          }
         limit='tag_Environment_DEV'
         credentials=@(
           9,
           36,
           37
          )
         }| ConvertTo-Json

        write-host $bodytest
        $body =@{
          definition = @{
            id = 68        
           }
          templateParameters = @{ sprint_number= "test123" }
        }| ConvertTo-Json
        write-host $body
        $params = @{'Uri' = ('https://hlsi01-poc.visualstudio.com/USHC_AMER_US_ADU_HSP_Ua3/_apis/build/builds?api-version=6.1-preview.6')
        'Headers'= @{'Authorization' = 'Basic ' + $pat}
        'Method'= 'Post'
        'ContentType' = 'application/json'
        'Body'= ($body)}
        $result = Invoke-RestMethod @params



