---
# Preety Print the  

resources:
  pipelines:
  - pipeline: securitylib # Name of the pipeline resource.
    source: TestCallPipeline # The name of the pipeline referenced by this pipeline resource.
    trigger: true # Run app-ci pipeline when any run of security-lib-ci completes

trigger:
  branches:
    include:
      - main

  tags:
    include:
      - '*'

parameters:
- name: Test_Paraj
  displayName: Sprint Number
  type: string
  default: noValue

variables:
- name: buildTimeStamp # will be set by script
- name: buildNum

stages:

- stage: Initialize
  pool: 
   name: Azure-GitHub
   demands:
    - agent.name -equals AZ-GH
  jobs:
  - job: Checkout
    timeoutInMinutes: 0
    displayName: 'Checkout'
    steps:
    - checkout: self 
      clean: true

    - script: |
       echo '1 - using dollar sign parens, p dot A_Parameter is now: ' $(parameters.Test_Paraj)
       echo '2 - using dollar sign double curly braces, p dot A_Parameter is now::' ${{ parameters.Test_Paraj }} '::'
       echo '3 - using dollar sign and only the var name: ' $(A_Parameter)
      displayName: 'Run a multi-line script'

  - job: variablesetup
    variables:     
      SPNum : ${{parameters.Test_Paraj}}

    steps:
    - task: PowerShell@2
      displayName: set variable buildTimeStamp and Build Number
      inputs:
       targetType: 'inline'
       script: |
        Write-Host ${{parameters.Test_Paraj}}
        Write-Host $(Test1)
   